env:
  global:
    - RUST_BACKTRACE=1
    - PATH=$PATH:$HOME/.cargo/bin
os:
  - linux
  - osx
language: rust
rust:
  - stable
sudo: false
branches:
  only:
    - master
cache:
  cargo: true
before_script:
  - curl -sSL https://github.com/maidsafe/QA/raw/master/travis/cargo_install.sh > cargo_install.sh
  - bash cargo_install.sh cargo-prune;
  - rustup component add rustfmt;
  - rustup component add clippy;
script:
  - set -x;
    if [[ -n "$TARGET" ]]; then
      TARGET_FLAG="--target $TARGET";
    fi &&
    cargo fmt -- --check &&
    # cargo check --verbose --all-targets $TARGET_FLAG &&
    # cargo clippy --verbose --all-targets $TARGET_FLAG &&
    cargo test --verbose --release $TARGET_FLAG
before_cache:
- cargo prune
