[package]
name = "sn_bindgen"
version = "0.13.9"
authors = [
  "Sean Marshallsay <srm.1708@gmail.com>",
  "Matthew Gregan <kinetik@flim.org>",
  "MaidSafe Developers <dev@maidsafe.net>"
]
description = "A library to automatically generate C, Java, and C# files from Rust source files."
readme = "README.md"
keywords = [ "c", "header", "ffi" ]
homepage = "https://github.com/maidsafe/sn_bindgen"
repository = "https://github.com/maidsafe/sn_bindgen"
documentation = "https://docs.rs/sn_bindgen"
license = "MIT OR BSD-3-Clause"
edition = "2018"

[lib]
name = "sn_bindgen"
path = "src/lib.rs"

[[bin]]
name = "bindgen"
doc = false
path = "src/bin/bindgen.rs"

[dependencies]
clap = "2.33.0"
toml = "~0.5.0"
Inflector = "~0.11.4"
jni = "~0.12.0"
quote = "~0.6.11"
rustfmt = "~0.10.0"
petgraph = "~0.4.13"
unwrap = "1.2.0"
proc-macro2 = "~0.4.27"

  [dependencies.syn]
  version = "~0.15.26"
  features = [ "parsing", "full", "derive", "proc-macro", "extra-traits" ]

[dev-dependencies]
colored = "1.6.0"
diff = "~0.1.11"
indoc = "~0.3.1"
